namespace App6
{
	[default_interface]
	runtimeclass SettingsViewModel : Microsoft.UI.Xaml.Data.INotifyPropertyChanged
	{
		SettingsViewModel();
		Boolean StealthMode;
		Boolean RestrictedTokens;
		Boolean LangOverride;
		Boolean IslandRestrictionsOverride;
		Boolean FrameRateLimitOverride;
		UInt32  FrameRateLimitValue;
		String  GamePath;
		Boolean CloseAsExit;
	}

}
